WF_opForUnits = [
  [configFile >> "CfgVehicles" >> "O_Soldier_F", 75],
  [configFile >> "CfgVehicles" >> "O_Soldier_lite_F", 50],
  [configFile >> "CfgVehicles" >> "O_Soldier_GL_F", 125],
  [configFile >> "CfgVehicles" >> "O_Soldier_AR_F", 75],
  [configFile >> "CfgVehicles" >> "O_Soldier_TL_F", 175],
  [configFile >> "CfgVehicles" >> "O_soldier_M_F", 200],
  [configFile >> "CfgVehicles" >> "O_Soldier_LAT_F", 200],
  [configFile >> "CfgVehicles" >> "O_medic_F", 100],
  [configFile >> "CfgVehicles" >> "O_soldier_repair_F", 100],
  [configFile >> "CfgVehicles" >> "O_soldier_exp_F", 150],
  [configFile >> "CfgVehicles" >> "O_helipilot_F", 75],
  [configFile >> "CfgVehicles" >> "O_Soldier_A_F", 125],
  [configFile >> "CfgVehicles" >> "O_Soldier_AT_F", 275],
  [configFile >> "CfgVehicles" >> "O_Soldier_AA_F", 275],
  [configFile >> "CfgVehicles" >> "O_engineer_F", 200],
  [configFile >> "CfgVehicles" >> "O_crew_F", 75],
  [configFile >> "CfgVehicles" >> "O_Pilot_F", 75],
  [configFile >> "CfgVehicles" >> "O_helicrew_F", 50],
  [configFile >> "CfgVehicles" >> "O_soldier_PG_F", 100],
  [configFile >> "CfgVehicles" >> "O_diver_F", 250],
  [configFile >> "CfgVehicles" >> "O_diver_TL_F", 250],
  [configFile >> "CfgVehicles" >> "O_diver_exp_F", 250],
  [configFile >> "CfgVehicles" >> "O_spotter_F", 175],
  [configFile >> "CfgVehicles" >> "O_sniper_F", 300],
  [configFile >> "CfgVehicles" >> "O_recon_F", 225],
  [configFile >> "CfgVehicles" >> "O_recon_M_F", 200],
  [configFile >> "CfgVehicles" >> "O_recon_LAT_F", 250],
  [configFile >> "CfgVehicles" >> "O_recon_medic_F", 225],
  [configFile >> "CfgVehicles" >> "O_recon_exp_F", 250],
  [configFile >> "CfgVehicles" >> "O_recon_JTAC_F", 275],
  [configFile >> "CfgVehicles" >> "O_recon_TL_F", 250],
  [configFile >> "CfgVehicles" >> "O_Soldier_AAR_F", 250],
  [configFile >> "CfgVehicles" >> "O_Soldier_AAT_F", 300],
  [configFile >> "CfgVehicles" >> "O_Soldier_AAA_F", 300],
  [configFile >> "CfgVehicles" >> "O_support_MG_F", 225],
  [configFile >> "CfgVehicles" >> "O_soldierU_F", 75],
  [configFile >> "CfgVehicles" >> "O_soldierU_AR_F", 75],
  [configFile >> "CfgVehicles" >> "O_soldierU_AAR_F", 75],
  [configFile >> "CfgVehicles" >> "O_soldierU_LAT_F", 200],
  [configFile >> "CfgVehicles" >> "O_soldierU_AT_F", 275],
  [configFile >> "CfgVehicles" >> "O_soldierU_AAT_F", 200],
  [configFile >> "CfgVehicles" >> "O_soldierU_AA_F", 275],
  [configFile >> "CfgVehicles" >> "O_soldierU_AAA_F", 200],
  [configFile >> "CfgVehicles" >> "O_soldierU_TL_F", 175],
  [configFile >> "CfgVehicles" >> "O_soldierU_medic_F", 100],
  [configFile >> "CfgVehicles" >> "O_soldierU_exp_F", 150],
  [configFile >> "CfgVehicles" >> "O_engineer_U_F", 100],
  [configFile >> "CfgVehicles" >> "O_soldierU_M_F", 200],
  [configFile >> "CfgVehicles" >> "O_soldierU_A_F", 125],
  [configFile >> "CfgVehicles" >> "O_SoldierU_GL_F", 125]
];

WF_bluForUnits = [
  [configFile >> "CfgVehicles" >> "B_Soldier_F", 75],
  [configFile >> "CfgVehicles" >> "B_Soldier_lite_F", 50],
  [configFile >> "CfgVehicles" >> "B_Soldier_GL_F", 125],
  [configFile >> "CfgVehicles" >> "B_Soldier_AR_F", 75],
  [configFile >> "CfgVehicles" >> "B_Soldier_TL_F", 175],
  [configFile >> "CfgVehicles" >> "B_soldier_M_F", 200],
  [configFile >> "CfgVehicles" >> "B_Soldier_LAT_F", 200],
  [configFile >> "CfgVehicles" >> "B_medic_F", 100],
  [configFile >> "CfgVehicles" >> "B_soldier_repair_F", 100],
  [configFile >> "CfgVehicles" >> "B_soldier_exp_F", 150],
  [configFile >> "CfgVehicles" >> "B_helipilot_F", 75],
  [configFile >> "CfgVehicles" >> "B_Soldier_A_F", 125],
  [configFile >> "CfgVehicles" >> "B_Soldier_AT_F", 275],
  [configFile >> "CfgVehicles" >> "B_Soldier_AA_F", 275],
  [configFile >> "CfgVehicles" >> "B_engineer_F", 200],
  [configFile >> "CfgVehicles" >> "B_crew_F", 75],
  [configFile >> "CfgVehicles" >> "B_Pilot_F", 75],
  [configFile >> "CfgVehicles" >> "B_helicrew_F", 50],
  [configFile >> "CfgVehicles" >> "B_soldier_PG_F", 100],
  [configFile >> "CfgVehicles" >> "B_diver_F", 250],
  [configFile >> "CfgVehicles" >> "B_diver_TL_F", 250],
  [configFile >> "CfgVehicles" >> "B_diver_exp_F", 250],
  [configFile >> "CfgVehicles" >> "B_spotter_F", 175],
  [configFile >> "CfgVehicles" >> "B_sniper_F", 300],
  [configFile >> "CfgVehicles" >> "B_recon_F", 225],
  [configFile >> "CfgVehicles" >> "B_recon_M_F", 200],
  [configFile >> "CfgVehicles" >> "B_recon_LAT_F", 250],
  [configFile >> "CfgVehicles" >> "B_recon_medic_F", 225],
  [configFile >> "CfgVehicles" >> "B_recon_exp_F", 250],
  [configFile >> "CfgVehicles" >> "B_recon_JTAC_F", 275],
  [configFile >> "CfgVehicles" >> "B_recon_TL_F", 250],
  [configFile >> "CfgVehicles" >> "B_Soldier_AAR_F", 250],
  [configFile >> "CfgVehicles" >> "B_Soldier_AAT_F", 300],
  [configFile >> "CfgVehicles" >> "B_Soldier_AAA_F", 300],
  [configFile >> "CfgVehicles" >> "B_support_MG_F", 225]
];

{
  missionNamespace setVariable ["WF_UNITS_" + (configName (_x select 0)), _x select 1];
} forEach WF_bluForUnits;

{
  missionNamespace setVariable ["WF_UNITS_" + (configName (_x select 0)), _x select 1];
} forEach WF_opForUnits;

WF_units = compileFinal preprocessFileLineNumbers "scripts\common\functions\WF_units.sqf";
